---
- name: "Install apt for Python3"
  apt:
    pkg: "python3-apt"
  when: "ansible_python_version is version_compare('3', '>=')"

- name: "Install apt for Python2"
  apt:
    pkg: "python-apt"
  when: "ansible_python_version is version_compare('3', '<')"

- name: "Add the anaconda gpg key"
  apt_key:
    url: "https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc"
    state: "present"

- name: "Add the anaconda debian repo"
  apt_repository:
    repo: "deb https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main"
    state: "present"
    filename: "conda"

- name: "Install Conda package manager"
  apt:
    update_cache: "yes"
    name: "conda"
    state: "present"
...
