---
- name: "Install Dependencies"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "gettext"
      - "libxtst6"

- name: "Configure Firewall"
  ufw:
    port: "{{ item }}"
    rule: "allow"
  with_items:
    - "6080"
    - "6443"

- name: "Create ArcGIS User"
  user:
    name:     "{{ arcgis_system_user }}"
    password: "{{ arcgis_system_pass }}"
    comment:  "ArcGIS System User"
    shell:    "/bin/bash"
    state:    "present"
    create_home: "yes"

- name: "Set resource limits for ArcGIS"
  template:
    src: "limits.conf"
    dest: "/etc/security/limits.conf"

- name: "Create ArcGIS directory"
  file:
    path:  "/srv/arcgis"
    state: "directory"
    owner: "arcgis"
    group: "staff"
    mode:  "u=rwX,g=rwXs,o=rX"
...
