---
- name: "Install Dependencies"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "gettext"
      - "python3-psycopg2"

- name: "Configure Firewall"
  ufw:
    port: "{{ item }}"
    rule: "allow"
  with_items:
    - "6080"
    - "6443"

- name: "Create ArcGIS User"
  user:
    name:        "{{ arcgis_system_user }}"
    comment:     "ArcGIS System User"
    shell:       "/bin/bash"
    state:       "present"
    create_home: "yes"
    home:        "/srv/arcgis"
# We are not setting the password here, as we do not know the crypted value

- name: "Set resource limits for ArcGIS"
  template:
    src: "limits.conf"
    dest: "/etc/security/limits.conf"

- name: "Configure webadaptor in Apache"
  template:
    src: "apache.conf"
    dest: "/etc/apache2/sites-enabled/conf.d/arcgis-webadaptor.conf"
  notify: "apache_restart"
...
