---
- name: "Install Dependencies"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "gettext"

- name: "Configure Firewall"
  ufw:
    port: "{{ item }}"
    rule: "allow"
  with_items:
    - "6080"
    - "6443"

- name: "Create ArcGIS User"
  user:
    name:        "{{ arcgis_system_user }}"
    comment:     "ArcGIS System User"
    shell:       "/bin/bash"
    state:       "present"
    create_home: "yes"
    home:        "/srv/arcgis"

- name: "Set resource limits for ArcGIS"
  template:
    src: "limits.conf"
    dest: "/etc/security/limits.conf"
